CREATE TABLE `sale` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `client_id` BIGINT NOT NULL,
  `total` DOUBLE NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_sale_client` FOREIGN KEY (`client_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB;
